# folder where the data is downloaded
data_root: /cluster/eriador/lhoellein/scannetpp

# Set True to render depth for iphone frames
render_iphone: False
render_iphone_undistorted: False
render_iphone_imu: True
# Set True to render depth for dslr frames
render_dslr: False
render_dslr_undistorted: False
render_novel_views: False

imu_every_nth_frame: 2  # 30 fps
downscale_factor: 8
save_rendered_rgb: False
save_rendered_depth: True

splits: [nvs_sem_train, nvs_sem_val]

# Specify scene ids if you want to render depth for specific scenes
# scene_ids: [355e5e32db]

# The near and far planes for the depth camera during rendering in meters.
near: 0.05
far: 20.0

# Output directory for the rendered depth images. If not given, the output will be saved to data folder in data_root
# output_dir: OUTPUT_DIR
