
# extract RGB frames
extract_rgb: true
# extract anonymization masks
extract_masks: false
# extract depth frames
extract_depth: false

only_keep_transforms_frames: false

# folder where the data is downloaded
data_root: /cluster/eriador/lhoellein/scannetpp

splits: [nvs_sem_train, nvs_sem_val]

scene_ids: [355e5e32db]
