# folder where the data is downloaded
data_root: /cluster/eriador/lhoellein/scannetpp

splits: [nvs_sem_train, nvs_sem_val]

scene_ids: [355e5e32db]

# The following paths should be given relative to the DATA_ROOT/iphone/
# If not given, will use the default directory defined in ScannetppScene class

# input_image_dir: rgb
# input_transforms_path: nerfstudio/transforms.json

# All use the relative path to DATA_ROOT/iphone/
out_image_dir: undistorted_images
out_transforms_path: nerfstudio/transforms_undistorted.json
